name: Check

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

env:
  TZ: Asia/Shanghai
  CONFIG: ${{ secrets.CONFIG }}

jobs:
  checkver:
    name: CheckVer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update package manager database
        run: sudo apt-get update
      - name: Install Dependence
        run: sudo apt-get install curl wget jq xxd libxml2-utils
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Git config
        run: |
          git config --local user.email "43134606+Ryanjiena@users.noreply.github.com"
          git config --local user.name "Ryanjiena"
      - name: Check
        run: sed -i 's/\r$//' check.sh && bash check.sh
      - name: Commit
        run: git commit -S -am "check"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
